# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: '^.*\.md$'
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
    -   id: terraform_tflint
        args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    -   id: terraform_trivy
        args:
        - --args=--config=__GIT_WORKING_DIR__/trivy.yaml
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
    -   id: actionlint
-   repo: local
    hooks:
    -   id: git-secrets
        name: git secrets
        entry: git secrets --scan
        language: system
        types: [text]
